UPLOAD_FOLDER = '/tmp/'
ALLOWED_EXTENSIONS = set(['pdf', 'xls'])
EXCEL_FILENAME = 'output.xls'
TABS = [
    'B.O.F. ET DIVERS',
    'BOF VIANDES FRAICHES',
    'BOISSONS',
    'BOULANGERIE-PATISSERIE',
    'EPICERIE POIDS',
    'EPICERIE UNITE',
    'FRUIT ET LEGUMES : POIDS',
    'FRUITS ET LEGUMES : UNITE',
    'SURGELES'
]